#theme: jekyll-theme-cayman
remote_theme: rundocs/jekyll-rtd-theme
title: OCamlJ
description: An IntelliJ Extension to implement OCaml functionnalities
lang: en

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
